### PR TITLE
platformio.ini + setVoice fix

### PR DESCRIPTION
**Pull request by tobozo**

### CODE REVIEW

**Comment by monopoldesign** [comment]
I have the audio libraries installed in a global folder. Therefore I wouldn't change the platform.ini. However, I would change the constant for the voice type to your suggestion. Thanks.

**Comment by tobozo** [comment]
Sorry, I added thoses missing libraries to the ini file so the project would become usable outside this perimeter e.g. built by a CI job, github action or webapp.

Should they be documented in a readme instead ?

**Comment by monopoldesign** [comment]
This project is in a very early stage. Once i have implemented a few useful applications, I'll add the readme, where I'll also link the libraries. In the meantime, feel free to change/improve it. I have e.g. added a keyboard input window yesterday, which has not been pushed yet. I'll do that tomorrow at the latest.

**Comment by tobozo** [comment]
I'm closing this PR, it's sending a notification every time I'm syncing my fork and you probably don't want that :-)

**Pull request closed without merging**
